### ISSUE TITLE
How to make synced files executable?

### ISSUE THREAD

**Issue by kickthemooon** [ksync/ksync#308]
All synced files have following permissions:
`-rw-r--r--`
and are not executable.

How to make synced files executable?

**Comment by timfallmk** [comment]
Do the remote permissions match the local permissions?

**Comment by timfallmk** [comment]
It does AFAIK

**Comment by p15r** [comment]
I experience a similar problem (fs permission issue).

An example folder in a container:
`drwxr-xr-x    1 nobody   nobody      4.0K Jun 18 17:28 scanner`

After I run `ksync create`:
`drwxrwx---    1 nobody   nobody      4.0K Jun 18 19:45 scanner`

This causes to break my service running in that container, because it runs (intentionally) under a different user than `nobody`. Any idea why this happens?

Version info
```
$ ksync version
ksync:
        Version:    Release
        Go Version: go1.13.6
        Git Commit: b2ca492
        Git Tag:    0.4.4
        Built:      Thu Feb 20 23:22:28 +0000 2020
        OS/Arch:    linux/amd64
service:
        Version:    corrupted-version
        Go Version: go1.13.6
        Git Commit: b2ca492
        Git Tag:    0.4.4
        Built:      Thu Feb 20 23:25:57 +0000 2020
```
And k8s via minikube v1.11.0:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by grampelberg** [comment]
It needs to be executable locally, the permissions are preserved across the sync.

**Comment by p15r** [comment]
@grampelberg I can confirm that insufficient local permissions were the problem. Thanks. 

Looking forward to new releases. ksync really speeds up my dev/deploy workflow! :smile:
